from app import create_app
from extensions import db
from models.evidence import EvidenceFile
from models.analysis import AnalysisResult
from models.pdf_report import PDFReport
from models.chain_of_custody import ChainOfCustody

app = create_app()

with app.app_context():
    print("=" * 50)
    print("DATABASE DIAGNOSTIC")
    print("=" * 50)
    
    # Check evidence files
    evidence_files = EvidenceFile.query.all()
    print(f"\nEvidence Files: {len(evidence_files)}")
    for ev in evidence_files:
        print(f"  - {ev.evidence_number}: {ev.original_filename} (Status: {ev.status})")
    
    # Check analysis results
    analyses = AnalysisResult.query.all()
    print(f"\nAnalysis Results: {len(analyses)}")
    for a in analyses:
        print(f"  - Evidence ID: {a.evidence_id}, Classification: {a.classification}, Score: {a.authenticity_score}%")
    
    # Check PDF reports
    reports = PDFReport.query.all()
    print(f"\nPDF Reports: {len(reports)}")
    for r in reports:
        print(f"  - {r.report_number}: {r.file_path} (Exists: {__import__('os').path.exists(r.file_path) if r.file_path else False})")
        print(f"    Evidence ID: {r.evidence_id}, Generated by: {r.generator.full_name if r.generator else 'N/A'}")
    
    # Check chain of custody
    coc_entries = ChainOfCustody.query.all()
    print(f"\nChain of Custody Entries: {len(coc_entries)}")
    for c in coc_entries:
        print(f"  - {c.action}: {c.description[:50] if c.description else 'N/A'}")
    
    # Check reports folder
    import os
    reports_dir = os.path.join(os.path.dirname(__file__), 'reports', 'output')
    if os.path.exists(reports_dir):
        pdf_files = [f for f in os.listdir(reports_dir) if f.endswith('.pdf')]
        print(f"\nPDF files in reports/output/: {len(pdf_files)}")
        for f in pdf_files:
            print(f"  - {f}")
    else:
        print(f"\nReports directory does not exist: {reports_dir}")